// this file is generated by script, don't modify it !!!
export const oracleFactoryChainlinkAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "string",
        "name": "symbol",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "feed",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "oracle",
        "type": "address"
      }
    ],
    "name": "CreateOracleChainlink",
    "type": "event"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" },
      { "internalType": "address", "name": "feed", "type": "address" }
    ],
    "name": "createOracle",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" }
    ],
    "name": "getFeed",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" }
    ],
    "name": "getOracle",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  }
]

