// this file is generated by script, don't modify it !!!
import { processMethod } from "../../shared/utils/index.js";
import { bg } from "../../shared/utils/index.js";

const isUnlocked = (klass) => {
  klass.prototype["isUnlocked"] = async function (accountAddress, poolAddress) {
    const allowance = await this.allowance(accountAddress, poolAddress)
    //console.log(accountAddress, poolAddress)
    const res = bg(allowance).gt(0)
    return res
  };
  return klass
};

export const ERC20Adapter = (klass) => {
    klass = processMethod(klass, 'totalSupply');
    //klass = processMethod(klass, 'balanceOf'); // use ERC20.decimals

    klass = isUnlocked(klass);
    return klass
}

export const chainlinkOracleAdapter= (klass) => {
    klass = processMethod(klass, 'getPrice');
    return klass
}

export const offChainOracleAdapter= (klass) => {
    klass = processMethod(klass, 'getPrice');
    return klass
}

export const offChainVolatilityOracleAdapter= (klass) => {
    klass = processMethod(klass, 'getVolatility');
    return klass
}
